- name: install baseline dependencies
  apt:
    force_apt_get: True
    name: "{{ telekom_debs }}"
    state: latest

- name: remove unneeded packages
  apt:
    force_apt_get: True
    name: "{{ telekom_remove_debs }}"
    state: absent
    autoremove: yes
    autoclean: yes
    purge: yes

- name: Gather the package package facts
  package_facts:
    manager: auto

- name: Print the package package facts
  debug:
    var: ansible_facts.packages
    