- name: Concatenate the Photon RPMs
  set_fact:
    telekom_photon_rpms: "{{ telekom_photon_rpms | join(' ') }}"

- name: install baseline dependencies
  command: tdnf install {{ telekom_photon_rpms }} -y
