---
# Helm version number
helm_version: '3.1.2'

# Mirror to download Helm from
helm_mirror: 'https://get.helm.sh'

# Dir where Helm should be installed
helm_install_dir: '/usr/local/share/helm'

# Directory to store files downloaded for Helm
helm_download_dir: "{{ x_ansible_download_dir | default(ansible_env.HOME + '/.ansible/tmp/downloads') }}"


telekom_rpms:
 - nfs-utils

telekom_debs:
 - nfs-common

telekom_photon_rpms:
 - nfs-utils


telekom_remove_rpms:


telekom_remove_debs:
 - telnet
 - build-essential
 - rsync
 - socat
 - tcpdump


telekom_remove_photon_rpms:
