# Use config version 2 to enable new configuration fields.
# Config file is parsed as version 1 by default.
version = 2

[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "{{ containerd_pause_image }}"

    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."*"]
          endpoint = ["https://harbor.sce-dcn.net/system,https://harbor.sce-dcn.net/system/,https://harbor.bremen.das-schiff.telekom.de/system,https://harbor.bremen.das-schiff.telekom.de/system/,https://harbor.das-schiff.telekom.de/system,https://harbor.das-schiff.telekom.de/system/"]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.elastic.co"]
          endpoint = ["https://harbor.sce-dcn.net/elastic,https://harbor.sce-dcn.net/elastic/,https://harbor.bremen.das-schiff.telekom.de/elastic,https://harbor.bremen.das-schiff.telekom.de/elastic/,https://harbor.das-schiff.telekom.de/elastic,https://harbor.das-schiff.telekom.de/elastic/"]
